site_name: Cucumber Diseases
site_description: "Dedicated practice to identify and improve your BDD code."
repo_url: https://github.com/Cucumber-Diseases
theme:
  name: 'material'
  logo: 'assets/smelly_cucumber_transparent.png'
  favicon: 'assets/smelly_cucumber_transparent.png'
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light-green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - content.code.annotate

nav:
  - Overview:
    - index.md
    - intro/contributors.md
  - Practice Repositories:
    - repos/index.md
    - repos/example_application.md
    - repos/java.md
    - repos/go.md
    - repos/python.md
    - repos/csharp.md
  - Cucumber Smells:
    - smells/index.md
    - smells/001-missing-then.md
    - smells/002-unused-given.md
    - smells/003-data-collector.md
    - smells/004-redundant-mirror-image.md
    - smells/005-intermediate-when-steps.md
    - smells/006-given-when-purpose-mismatch.md
    - smells/007-rotting-steps.md
    - smells/008-singular-plural-logic-clones.md
    - smells/009-dead-steps.md
    - smells/010-hardcoded-parameters.md
    - smells/011-active-sideeffects-in-then-step.md
    - smells/012-dependence-on-class-state.md
    - smells/013-test-code-impurity.md
    - smells/014-multiple-behaviours-in-scenario.md
  - Deliberate Exercise:
    - exercise/index.md
    - exercise/ex-001-missing-then.md
    - exercise/ex-002-unused-given.md
    - exercise/ex-003-data-collector.md
    - exercise/ex-004-redundant-mirror-image.md
    - exercise/ex-005-intermediate-when-steps.md
    - exercise/ex-006-given-when-purpose-mismatch.md
    - exercise/ex-007-rotting-steps.md
    - exercise/ex-008-singular-plural-logic-clones.md
    - exercise/ex-009-dead-steps.md
    - exercise/ex-010-hardcoded-parameters.md
    - exercise/ex-011-active-sideeffects-in-then-step.md
    - exercise/ex-012-dependence-on-class-state.md
    - exercise/ex-013-test-code-i mpurity.md
    - exercise/ex-014-scenario-overload.md
  - Contributing:
    - contrib/index.md
    - contrib/add_smell.md
    - contrib/add_repo.md

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
