site_name: Cucumber Diseases
site_description: "Dedicated practice to identify and improve your BDD code."
theme:
  name: 'material'
nav:
  - index.md
  - howto.md
  - practice-repos.md
  - smells.md
  - contribution.md