name: MkDocs
on: [push]
permissions:
  contents: write
jobs:
  deploy-mkdocs-ghpages:
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Deploy MkDocs
         uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
