name: MkDocs
on: [push]
jobs:
  deploy-mkdocs-ghpages:
     runs-on: ubuntu-latest
     steps:
       - run: pip install mkdocs
       - name: Check out repository code
         uses: actions/checkout@v4
       - run: mkdocs gh-deploy
          
