name: MkDocs
on: [push]
permissions:
  contents: write
jobs:
  deploy-mkdocs-ghpages:
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Install requirements
         run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
       - name: Deploy MkDocs
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          remote_repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git remote rm origin
          git remote add origin "${remote_repo}"
          mkdocs gh-deploy --force
          
